name: Hello World
author: Dheeraj Patil
description: Greet someone and record time
inputs: 
    who_to_greet:
        description: "who to greet"
        required: true
        default: "Dheeraj"
outputs:
    time:
        description: Time of greeting
runs:
    using: "node16"
    main: dist/index.js
    pre: "setup.js"
    pre-if: runner.os=='linux'
    post: "cleanup.js"
    post-if: runner.os=='linux'