name: concurrency
on:
 workflow_dispatch: 
    inputs:
        Environment:
            description: Environments
            type: environment
            required: true
concurrency: 
    group: ${{github.workflow}}-${{inputs.Environment}}
    cancel-in-progress: true
jobs:
    Concurrent-Running:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello"

       