name: Docker-WF
on: [workflow_dispatch]
jobs:
    Initialize-Docker-Container:
        runs-on: ubuntu-latest
        container: 
            image: node:23-alpine3.19
            env:
                username: Dheeraj
                
        steps:
            - name: Log Node and OS Version
              run: |
                node -v
                cat /etc/os-release
                echo $username

            