name: Vars-Secrets-Testing
on: [push, workflow_dispatch]
jobs:
    Check-vars-secrets:
        runs-on: ${{vars.JOB_RUNNER}}
        environment: Production
        env: 
            BOOLEAN_SECRET: ${{secrets.BOOLEAN_SECRET}}
            ORG_LEVEL_VAR: ${{vars.ORG_LEVEL_VAR}}
            ENV_LEVEL_VAR: ${{vars.ENV_LEVEL_VAR}}
        steps:
            - name: log secrets and variables
              run: |
               echo $BOOLEAN_SECRET
               echo $ORG_LEVEL_VAR
               echo $ENV_LEVEL_VAR

